name: docs
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Run-macOS-installation-process:
    name: macOS installation process
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install these packages using Homebrew
        run: brew install hugo ruby git bmake
      - name: Add ruby to the path
        run: |
          echo 'export GEM_PATH="/usr/local/lib/ruby/gems/3.1.0/bin"' >> ~/.bashrc
          echo 'export PATH="$GEM_PATH:/usr/local/opt/ruby/bin:$PATH"' >> ~/.bashrc
          . ~/.bashrc
      - name: Install these packages using RubyGem
        run: gem install rouge asciidoctor asciidoctor-pdf asciidoctor-epub3
      - name: Install a local working copy of the documentation from the FreeBSD repository
        run: git clone https://git.FreeBSD.org/doc.git ~/doc
      - name: XXX Patch Makefile
        run: cp $GITHUB_WORKSPACE/Makefile ~/doc/documentation
      - name: XXX Patch asciidoctor.sh
        run: cp $GITHUB_WORKSPACE/asciidoctor.sh ~/doc/documentation/tools
      - name: Run bmake in the top-level directory of the documentation
        run: |
          cd ~/doc/documentation
          bmake build ASCIIDOCTOR_CMD=${GEM_PATH}/asciidoctor ROUGIFY_CMD=${GEM_PATH}/rougify
          #- uses: actions/upload-artifact@master
          #  with:
          #    name: documentation
          #    path: ~/doc/documentation/public
